services:
  send-back:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      OCAML_WORKER_COMMAND: /app/worker
    ports:
      - 9119:8080
  send-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SANDBOX_BACKEND_PORT: "9119"
    ports:
      - 5173:80
